//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_de_ventas.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public int id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<long> Cedula { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
    }
}
